apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "employees"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-script
          configMap:
            name: mysql-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: final
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS employees;
    USE employees;
    CREATE TABLE IF NOT EXISTS employee (
      emp_id INT PRIMARY KEY,
      first_name VARCHAR(50),
      last_name VARCHAR(50),
      primary_skill VARCHAR(100),
      location VARCHAR(100)
    );
