apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CLO835
  namespace: final
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: CLO835-binding
  namespace: final
subjects:
  - kind: ServiceAccount
    name: clo835
    namespace: final
roleRef:
  kind: Role
  name: CLO835
  apiGroup: rbac.authorization.k8s.io
