apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # echo -n "your_username" | base64
  # echo -n "your_password" | base64
  username: cm9vdA== # root
  password: cGFzc3dvcmQ= # password
