apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: clo835-final-project
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/YOUR_USERNAME/clo835_project
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clo835-final-project
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: clo835-final-project
  targetNamespace: final
