name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: clo835-final-project

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -c "import app; print('App imports successfully')"
          echo "Basic functionality test passed"

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if it doesn't exist
        run: |
          # Check if repository exists, if not create it
          if ! aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }} 2>/dev/null; then
            echo "Repository ${{ env.ECR_REPOSITORY }} does not exist. Creating it..."
            aws ecr create-repository \
              --repository-name ${{ env.ECR_REPOSITORY }} \
              --region ${{ env.AWS_REGION }} \
              --image-scanning-configuration scanOnPush=true \
              --encryption-configuration encryptionType=AES256
            echo "Repository ${{ env.ECR_REPOSITORY }} created successfully!"
          else
            echo "Repository ${{ env.ECR_REPOSITORY }} already exists."
          fi

      - name: Clean up existing images
        run: |
          echo "Cleaning up existing images in repository..."
          # Get list of image digests
          IMAGE_DIGESTS=$(aws ecr describe-images \
            --repository-name ${{ env.ECR_REPOSITORY }} \
            --region ${{ env.AWS_REGION }} \
            --query 'imageDetails[].imageDigest' \
            --output text 2>/dev/null || echo "")

          if [ ! -z "$IMAGE_DIGESTS" ]; then
            echo "Found existing images. Deleting them..."
            # Delete all images in the repository
            aws ecr batch-delete-image \
              --repository-name ${{ env.ECR_REPOSITORY }} \
              --region ${{ env.AWS_REGION }} \
              --image-ids $(aws ecr describe-images \
                --repository-name ${{ env.ECR_REPOSITORY }} \
                --region ${{ env.AWS_REGION }} \
                --query 'imageDetails[].{imageDigest:imageDigest}' \
                --output json | jq -r '.[] | "imageDigest=" + .imageDigest' | tr '\n' ' ')
            echo "Existing images deleted successfully!"
          else
            echo "No existing images found."
          fi

      - name: Build, tag, and push image to Amazon ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT
